public with sharing class CRAN_VAS_KER_Constants_CLS {
    
    public static final String OPP_OBJETIVO_MKT_RT 					= 'CRAN_VAS_MAQ_Objetivo_Marqueting';
    public static final String OPP_VENTA_RT 						= 'CRAN_VAS_MAQ_Venta';
    public static final String OPP_OBJETIVO_SIST_RT 				= 'CRAN_VAS_MAQ_Objetivo_Sistematica';
    public static final String OPP_VENTA_GANADA_RT 					= 'CRAN_VAS_MAQ_VentaGanada';
    public static final String OPP_VENTA_CANCELADA_RT 				= 'CRAN_VAS_MAQ_VentaCancelada';
    public static final String OPP_VENTA_PERDIDA_RT 				= 'CRAN_VAS_MAQ_VentaPerdida';
    
    public static final String OPP_CANCELLED_STAGE					= 'Cancelled';															 
    
    public static final String CAMPAIGN_MKT_RT 					= 'CRAN_VAS_MAQ_MarquetingRecordType';
    public static final String CAMPAIGN_SIST_RT 				= 'CRAN_VAS_MAQ_SistComRecordType';
    
    public static final String CALENDARITEM_FESTIVO_RT 				= 'CRAN_VAS_MAQ_Festivo';
    public static final String CALENDARITEM_VACACIONES_RT			= 'CRAN_VAS_MAQ_Vacaciones';
    public static final String CALENDARITEM_VISITA_RT 				= 'CRAN_VAS_MAQ_Visita';
    public static final String CALENDARITEM_AUSENCIA_RT 			= 'CRAN_VAS_MAQ_Ausencia';
    public static final String CALENDARITEM_STATUS_PLANNED 			= 'Planificada';
    public static final String CALENDARITEM_STATUS_WAITING 			= 'Cliente en espera';
    public static final String CALENDARITEM_STATUS_PROGRESS 		= 'En curso';
    public static final String CALENDARITEM_STATUS_PENDING 			= 'Pendiente de cierre';
    public static final String CALENDARITEM_STATUS_CLOSED 			= 'Cerrada';
    public static final String CALENDARITEM_STATUS_CANCELLED 		= 'Anulada';    
    
    public static final String CAMPAIGNMEMBER_STATUS_NOTWORKED 		= 'No Trabajado';
    public static final String CAMPAIGNMEMBER_STATUS_WORKED 		= 'Trabajado';
    public static final String CAMPAIGNMEMBER_STATUS_WON 			= 'Ganado';
    public static final String CAMPAIGNMEMBER_ORIGEN_POTENTIAL 		= 'Potencial';
    public static final String CAMPAIGNMEMBER_ORIGEN_NEW 			= 'Nuevo';
    
    public static final String USER_PROFILE_DIRECTOR_OFICINA			= 'Banking Office Director';
    public static final String USER_PROFILE_DIRECTOR_OFICINA_PRIVADO	= 'Private Banking Office Director';
    public static final String USER_PROFILE_DIRECTOR					= 'Banking Director';
    public static final String USER_PROFILE_DIRECTOR_PRIVADO			= 'Private Banking Director';
    public static final String USER_PROFILE_GESTOR						= 'Banking Manager';
    public static final String USER_PROFILE_GESTOR_PRIVADO				= 'Private Banking Manager';
    public static final String USER_PROFILE_MARKETING					= 'Marketing CA';
    
    	
}