public with sharing class CRAN_VEC_ADV_Asset_CLS {
 	private Long assetID;
 	private Long cranCode;
 	private Long assetBU;
                          
	public Long getAssetID(){
		return assetID;
	}

	public void setAssetID(Long assetID){
		this.assetID = assetID;
	}

	public Long getCranCode(){
		return cranCode;
	}

	public void setCranCode(Long cranCode){
		this.cranCode = cranCode;
	}

	public Long getAssetBU(){
		return assetBU;
	}

	public void setAssetBU(Long assetBU){
		this.assetBU = assetBU;
	}
}