public with sharing class CRAN_VEC_ADV_ObjRS_CLS {
        private String avqId;
        private List<CRAN_VEC_ADV_keyList_CLS> keyList;

        public String getAvqId(){
            return avqId;
        }

        public void setAvqId(String avqId){
            this.avqId = avqId;
        }

        public List<CRAN_VEC_ADV_keyList_CLS> getKeyList(){
            return keyList;
        }

        public void setKeyList(List<CRAN_VEC_ADV_keyList_CLS> keyList){
            this.keyList = keyList;
        }
}