/*************************************************************************************
Company         : VASS
Version         : 1.0 
Created Date    : 21 Nov 2017
Function        : Error class 

Modification Log :
-------------------------------------------------------------------------------------
* Developer                   Date                   Description
* -----------------------------------------------------------------------------------
* Nacho Hita            2017/11/21              	 Created the file - Original Version
*************************************************************************************/
	
public with sharing class CRAN_VAS_ON_JSONAnswer_CLS {
    public String answer			{get; set;}
    public String code		        {get; set;}
    public String description       {get; set;} 
}