public with sharing class CRAN_VEC_ADV_ObjList_CLS {
        private String objType;
        private List<CRAN_VEC_ADV_Obj_CLS> obj; 
   

        public String getObjType() {
            return objType;
        }

        public void setObjType(String objType) {
            this.objType = objType;
        }

        public List<CRAN_VEC_ADV_Obj_CLS> getObj() {
            return obj;
        }

        public void setObj(List<CRAN_VEC_ADV_Obj_CLS> obj) {
            this.obj = obj;
        }
}