/**
 * CRAN_VEC_ADV_PrintDocumentPdfRQ_CLS POJO for avaloq Rest services
 *
 * Fecha: 28/11/2016
 * @author  Julian Gonzalez Garcia (Vector ITC)
 * @version 1.0
 *
*/

public with sharing class CRAN_VEC_ADV_PrintDocumentPdfRQ_CLS {
	
	private String idCustomForm;

    public String getIdCustomForm() {
        return idCustomForm;
    }
    public void setIdCustomForm(String version) {
        this.idCustomForm = version;
    }
}