public with sharing class CRAN_VEC_ADV_Obj_getForms_CLS {
        private String avqId;
        //private String date;
        private String type;
        private String version;
        private String status;

        public String getAvqId(){
            return avqId;
        }

        public void setAvqId(String avqId){
            this.avqId = avqId;
        }

        /*public String getDate(){
            return date;
        }

        public void setDate(String date){
            this.date = date;
        }*/

        public String getVersion(){
            return version;
        }

        public void setVersion(String version){
            this.version = Version;
        }

        public String getStatus(){
            return status;
        }

        public void setStatus(String status){
            this.status = status;
        }

        public String getType(){
            return type;
        }

        public void setType(String type){
            this.type = type;
        }
}