public class CRAN_ICA_KER_Campaign_CLS {

   /* public static String getDataSalesCampaign(Id campaignId){
          
        //return CRAS_ICA_ASS_Helpers_CLS.getDataFromWS('CRAN_ICA_KER_campaignSalesRest/' + campaignId);
        
        return CRAS_ICA_ASS_Helpers_CLS.getDataFromWS('CRAN_ICA_KER_campaignSalesRest/' + campaignId, 20000);

    }
    
    public static String getDataMembersCampaign(Id campaignId){
          
        //return CRAS_ICA_ASS_Helpers_CLS.getDataFromWS('CRAN_ICA_KER_campaignMembersRest/' + campaignId);
        
        String result = CRAS_ICA_ASS_Helpers_CLS.getDataFromWS('CRAN_ICA_KER_campaignMembersRest/' + campaignId, 20000);
        
        return result;

    }   */
    
}