public with sharing class CRAN_VEC_ADV_Trade_CLS {
	public String warning{get;set;}
	public String estimQty{get;set;}
	public String effQty{get;set;}
	public String assetId{get;set;}
	public String assetBuId{get;set;}
	public String assetName{get;set;}
	public String price{get;set;}
	public String curry{get;set;}
	public String marketId{get;set;}
	public String marketBuId{get;set;}
	public String marketName{get;set;}
	public String amount{get;set;}
	public String cost{get;set;}
	public String maccId{get;set;}
	public String maccName{get;set;}
	public String mnyDrv{get;set;}
	public String gen{get;set;}
	public String extl{get;set;}
	public String aggrPos{get;set;}
}