global class CRAN_ICA_KER_CampaignSales_DTO {

      /*  public String name;
    	public String bp;
    	public String status;
        public String campaignName;
    	public String ramo;
        public String advisor;
        public String totalOpportunity;
        public String amount;
        public String idOperacionComercial;
        public String accountName;
        public String closeDate;
        public String recordTypeName;
	*/    
}